### PR TITLE
fix null type parsing and add null tests

### LINKED ISSUE #475: null type everywhere
I've run into a few problems with using the `null` type, make sure it can be used in parameters, return types, records, and variants.

### PR DESCRIPTION
**Pull request by bdemann**
Fixes #475

### CODE REVIEW

File: examples/null_example/src/null_example.ts [hunk 1]
```diff
@@ -0,0 +1,63 @@
+import { int, Query, Update, Variant } from 'azle';
+
+type partially_null_object = {
```
Comment (lastmjs) [inline examples/null_example/src/null_example.ts:3]: The convention for type names is to have them by uppercase camelcase, so this would be `PartiallyNullObject`

File: examples/null_example/src/null_example.ts [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    first_item: null;
+    second_item: null;
+    third_item: null;
+};
+
+export function null_function(param: null): Query<null> {
+    return param;
+}
+
+export function get_partial_null_record(): Query<partially_null_object> {
```
Comment (lastmjs) [inline examples/null_example/src/null_example.ts:24]: If we're calling this `get_partial_null_record` then I think we should name the type `PartiallyNullRecord`

**Review by lastmjs — CHANGES_REQUESTED** [review]
Just a couple name changes

File: examples/null_example/src/null_example.ts (hunk 2 above)
Comment (bdemann) [reply examples/null_example/src/null_example.ts:24]: Sounds good, and I'll change the function to ```get_partially_null_record``` while I'm at it

**Review by lastmjs — DISMISSED** [review]
